// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQthLXRZeR1FD04iTgkB9eJ5R6Ed0sxFA',
    appId: '1:387654486574:web:b463d0ee1c514d3a066dbf',
    messagingSenderId: '387654486574',
    projectId: 'foodex2',
    authDomain: 'foodex2.firebaseapp.com',
    storageBucket: 'foodex2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuGGwVkwrLPn4Rm2fZKN_bvSuwNnyF8L0',
    appId: '1:387654486574:android:fa7db2b1b525becd066dbf',
    messagingSenderId: '387654486574',
    projectId: 'foodex2',
    storageBucket: 'foodex2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG3JZ5mWZTNoPVLiC74FXEU6mVSG2dWTQ',
    appId: '1:387654486574:ios:03435b8801aee6bc066dbf',
    messagingSenderId: '387654486574',
    projectId: 'foodex2',
    storageBucket: 'foodex2.appspot.com',
    iosBundleId: 'com.example.foodex2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG3JZ5mWZTNoPVLiC74FXEU6mVSG2dWTQ',
    appId: '1:387654486574:ios:8b0039d46b78a621066dbf',
    messagingSenderId: '387654486574',
    projectId: 'foodex2',
    storageBucket: 'foodex2.appspot.com',
    iosBundleId: 'com.example.foodex2.RunnerTests',
  );
}
